### ISSUE TITLE
MD5 Hash Decrypt

### ISSUE THREAD

**Issue by ashraful1978** [Adkali/Hashget#1]
Dear Concern,
I have check to your python script; it is easy to use and find output smoothly. It is great software; but unable to my MD5 hash could not find my password: 2048bfd2430726c9b83a7555d47ac94a. I have check with hashcat.exe 7 all mix character & 10 lowercase uppercase 12 digit; but could no be found it. Could you please checked MD5 Hash to cracking password; if you have found password it will help to me. Also i will donate & contribute accordingly.

Regards,

Mohammad Ashraful Alam

**Comment by Adkali** [comment]
Hey, sorry for delay.
this code based on users input and web sources.
It gathers a couple sites as it prints the results without the need for searching. I believe there might be some hashes that won't be found as clearText, but again - it all lays on existing sources.

Thanks for using, hope to make it even better :)
